### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WarrenBradfield** [rajkavinchetty/Google-Maps-API-with-PHP-MySQL#2]
Hi, for some reason I am getting the following message.

Notice: Undefined index: service in C:\xampp\htdocs\Maps\maps.php on line 3
`$work=$_GET["service"];`

Fatal error: Call to a member function fetch_assoc() on boolean in C:\xampp\htdocs\Maps\maps.php on line 12

**Comment by neelapandit** [comment]
Same issue :( ... please reply

**Comment by rajkavinchetty** [comment]
Glad that worked for you ;) Have a Nice Day ahead bro!
